name: Build Docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          tags: user/app:latest
